### ISSUE TITLE
Environment variables not being substituted

### ISSUE THREAD

**Issue by Freekers** [Slidem/inplace-envsubst-action#2]
Hi,

I'm trying to use your Github Action to replace two environment variables with the value of Github Secrets in a .sh file before building and pushing a Docker image. However, the variables are not being substituted. Instead they are left blank. The filename that contains the environment variables that need to be substituted is named 'entrypoint.sh' and is located in the root of my repository. I've setup your Github Action as follows:

```
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      - name: Variable Substitution
        uses: Slidem/inplace-envsubst-action@v1.0.0
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        with:
          fail_on_missing_variables: "true"
          search_input: |
            {
              "files": ["entrypoint.sh"],
              "depth": 1
            }

```
Source: https://github.com/Freekers/docker-ggcombatcarnage/blob/main/.github/workflows/automation.yml

And the entrypoint.sh file containing the environment variables that need to be substituted looks like this:
```
#!/bin/bash -ex

[ "$UID" != 0 ] || {
    mkdir -p ~user/Steam
    chown user: ~user/Steam
    runuser -u user "$0" "$@"
    exit 0
}

GAMEDIR="$HOME/Steam/steamapps/common/Gas Guzzlers Combat Carnage/Bin32"

cd "$HOME"
STEAMCMD="./steamcmd.sh +@sSteamCmdForcePlatformType windows +login ${STEAM_USERNAME} ${STEAM_PASSWORD} $STEAMCMD"

# eval to support quotes in $STEAMCMD
eval "$STEAMCMD +app_update 596620 +quit"

rm -f /tmp/.X1-lock
Xvfb :1 -screen 0 800x600x24 &
export WINEDLLOVERRIDES="mscoree,mshtml="
export DISPLAY=:1

cd "$GAMEDIR"

[ "$1" = "bash" ] && exec "$@"

wine ./GGDedicatedServer.exe
```
Source:  https://github.com/Freekers/docker-ggcombatcarnage/blob/main/entrypoint.sh

Why aren't `${STEAM_USERNAME}` and  `${STEAM_PASSWORD}` being substituted for their values stored as Github Secrets?

Thanks

**Comment by Slidem** [comment]
Hello,

Hmm interesting, let me double check it and get back to you by the end of today.

**Comment by Slidem** [comment]
Hey, just took a quick look...

I think you are missing just a step before the action:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
```

Git hub action just runs a docker container and executes your command. But it needs to checkout your code first ... unfortunatelly this doesn't happen automatically, you have to tell github actions to check out your code.


Can you please try again and let me know if it works ?

Full example of your workflow:

```
name: Build and Push Docker Image
on: 
 push:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 11 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Variable Substitution
        uses: Slidem/inplace-envsubst-action@v1.0.0
        env:
          STEAM_USERNAME: "${{ secrets.STEAM_USERNAME }}"
          STEAM_PASSWORD: "${{ secrets.STEAM_PASSWORD }}"
        with:
          fail_on_missing_variables: "true"
          search_input: |
            {
              "files": ["entrypoint.sh"],
              "depth": 1
            }
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: freekers/docker-ggcombatcarnage:latest,freekers/docker-ggcombatcarnage:${{ github.run_number }}
```

**Comment by Slidem** [comment]
Also, make sure to use the latest version v1.2.2 ^^

**Comment by Freekers** [comment]
Thanks for the quick reply and your help so far, I appreciate it 👍 

I implemented the checkout step and updated the version of your Github Action, but sadly it's still substituting them with blanks.
Here's the output of my Docker container:

```
eval './steamcmd.sh +@sSteamCmdForcePlatformType windows +login    +app_update 596620 +quit'
```
As you can see there are two white spaces between +login and +app_update where the username and password should be.

Any ideas :) ?

Thanks!

**Comment by Slidem** [comment]
Try also with uses like this (using "uses"):

```
- name: Test action
        uses: ./
        env:
          COOL: "test value"
          blacklisted: "blacklisted"
          whitelisted: "whitelisted"
``` 
to make sure you are on the root directory.

**Comment by Freekers** [comment]
I found the issue... and it has nothing to do with your code/action.

Apparently the `docker/build-push-action@v2` step checks out the code by itself automatically, unless you specifically tell it not to do so. So what was happening was is that I checked out the code using `actions/checkout@v2`, did the variable substitution, but then the `docker/build-push-action@v2` step would checkout the code _again_ and basically render the previous steps useless.

To fix this, all I needed to do was add `context: .` to the `docker/build-push-action@v2` step, which basically tells it not to checkout the code again, but build the image using the code that's already checked out. The automation.yml looks like this now:

```
name: Build and Push Docker Image
on: 
 push:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 11 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Variable Substitution
        uses: Slidem/inplace-envsubst-action@v1.2.2
        env:
          STEAM_USERNAME: "${{ secrets.STEAM_USERNAME }}"
          STEAM_PASSWORD: "${{ secrets.STEAM_PASSWORD }}"
        with:
          fail_on_missing_variables: "true"
          search_input: |
            {
              "files": ["entrypoint.sh"],
              "depth": 1
            }
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: freekers/docker-ggcombatcarnage:latest,freekers/docker-ggcombatcarnage:${{ github.run_number }}
```

Sorry for wasting your time on this, I'm still new to Github Actions.
